-- USERS
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(255) NOT NULL,
                                     login VARCHAR(255) NOT NULL,
                                     name VARCHAR(255),
                                     birthday DATE
);

-- MPA RATINGS
CREATE TABLE IF NOT EXISTS mpa_ratings (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name VARCHAR(10) NOT NULL UNIQUE
);

-- FILMS
CREATE TABLE IF NOT EXISTS films (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(1000),
                                     release_date DATE NOT NULL,
                                     duration INTEGER NOT NULL,
                                     mpa_id BIGINT NOT NULL,
                                     CONSTRAINT fk_films_mpa FOREIGN KEY (mpa_id)
                                         REFERENCES mpa_ratings(id)
);

-- GENRES
CREATE TABLE IF NOT EXISTS genres (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(100) NOT NULL UNIQUE
);

-- FILM_GENRES (many-to-many)
CREATE TABLE IF NOT EXISTS film_genres (
                                           film_id BIGINT NOT NULL,
                                           genre_id BIGINT NOT NULL,
                                           PRIMARY KEY (film_id, genre_id),
                                           CONSTRAINT fk_fg_film FOREIGN KEY (film_id)
                                               REFERENCES films(id)
                                               ON DELETE CASCADE,
                                           CONSTRAINT fk_fg_genre FOREIGN KEY (genre_id)
                                               REFERENCES genres(id)
                                               ON DELETE CASCADE
);

-- LIKES (many-to-many)
CREATE TABLE IF NOT EXISTS likes (
                                     film_id BIGINT NOT NULL,
                                     user_id BIGINT NOT NULL,
                                     PRIMARY KEY (film_id, user_id),
                                     CONSTRAINT fk_likes_film FOREIGN KEY (film_id)
                                         REFERENCES films(id)
                                         ON DELETE CASCADE,
                                     CONSTRAINT fk_likes_user FOREIGN KEY (user_id)
                                         REFERENCES users(id)
                                         ON DELETE CASCADE
);

-- FRIENDSHIPS
CREATE TABLE IF NOT EXISTS friendships (
                                           user_id BIGINT NOT NULL,
                                           friend_id BIGINT NOT NULL,
                                           PRIMARY KEY (user_id, friend_id),
                                           CONSTRAINT fk_friend_user FOREIGN KEY (user_id)
                                               REFERENCES users(id)
                                               ON DELETE CASCADE,
                                           CONSTRAINT fk_friend_friend FOREIGN KEY (friend_id)
                                               REFERENCES users(id)
                                               ON DELETE CASCADE
);

-- DIRECTORS
CREATE TABLE IF NOT EXISTS directors (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(255) NOT NULL
);

--FILM_DIRECTORS (many-to-many)
CREATE TABLE IF NOT EXISTS film_directors (
                                              film_id BIGINT NOT NULL,
                                              director_id BIGINT NOT NULL,

                                              PRIMARY KEY (film_id, director_id),

                                              CONSTRAINT fk_fd_film FOREIGN KEY (film_id)
                                                  REFERENCES films(id)
                                                  ON DELETE CASCADE,

                                              CONSTRAINT fk_fd_director FOREIGN KEY (director_id)
                                                  REFERENCES directors(id)
                                                  ON DELETE CASCADE
);

--REVIEWS
CREATE TABLE IF NOT EXISTS reviews (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       content TEXT NOT NULL,
                                       is_positive BOOLEAN NOT NULL,
                                       user_id BIGINT NOT NULL,
                                       film_id BIGINT NOT NULL,

                                       CONSTRAINT fk_review_user FOREIGN KEY (user_id)
                                           REFERENCES users(id)
                                           ON DELETE CASCADE,

                                       CONSTRAINT fk_review_film FOREIGN KEY (film_id)
                                           REFERENCES films(id)
                                           ON DELETE CASCADE
);

--REVIEW_LIKES
CREATE TABLE IF NOT EXISTS review_likes (
                                            review_id BIGINT NOT NULL,
                                            user_id BIGINT NOT NULL,
                                            is_like BOOLEAN NOT NULL,

                                            PRIMARY KEY (review_id, user_id),

                                            CONSTRAINT fk_rl_review FOREIGN KEY (review_id)
                                                REFERENCES reviews(id)
                                                ON DELETE CASCADE,

                                            CONSTRAINT fk_rl_user FOREIGN KEY (user_id)
                                                REFERENCES users(id)
                                                ON DELETE CASCADE
);

-- EVENTS
CREATE TABLE IF NOT EXISTS events (
                                      event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      user_id BIGINT NOT NULL,
                                      event_type VARCHAR(10) NOT NULL,   -- LIKE / REVIEW / FRIEND
                                      operation VARCHAR(10) NOT NULL,    -- ADD / REMOVE / UPDATE
                                      entity_id BIGINT NOT NULL,
                                      created_at TIMESTAMP NOT NULL,

                                      CONSTRAINT fk_event_user FOREIGN KEY (user_id)
                                          REFERENCES users(id)
                                          ON DELETE CASCADE
);